apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-image
  namespace: default
spec:
  selector:
    matchLabels:
      app: hello-image-app
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-image-app
    spec:
      containers:
        - name: hello-image-app
          image: docker.io/mhussain78/hello-flux:0.0.53 # {"$imagepolicy": "flux-system:hello-image"}
          ports:
            - containerPort: 8080
