apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: hello-image
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: hello-image
  policy:
    semver:
      range: 0.0.x