---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hello-family
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kubernetes/fluxcd/repositories/hello-family
  prune: true
  sourceRef:
    kind: GitRepository
    name: hello-family
