apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: hello-flux
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: fluxcd-2022
  url: https://github.com/mhussain78/flux-bootstrap.git