apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hello-flux
  namespace: default
spec:
  interval: 15m
  path: "./kubernetes/fluxcd/repositories/hello-flux"
  prune: true
  sourceRef:
    kind: GitRepository
    name: hello-flux