apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hello-flux
  namespace: default
spec:
  interval: 15m
  path: "./kubernetes/fluxcd/repositories/hello-flux"
  prune: true
  sourceRef:
    kind: GitRepository
    name: hello-flux
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: github-dispatch
  namespace: default
spec:
  type: githubdispatch
  address: https://github.com/mhussain78/fluxcd-installation-test
  secretRef:
    name: api-token
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: github-dispatch
  namespace: default
spec:
  summary: "staging (us-west-2)"
  providerRef:
    name: github-dispatch
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: 'hello-flux'