apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: hello-image
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: fluxcd-2022
  secretRef:
    name: hello-image
  url: ssh://git@github.com/flux-bootstrap.git