name: workflow_02
on: [workflow_dispatch]
jobs:
  cypress-run:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.event }} "
      - run: echo "Hello :-)"
      - name: Get code
        uses: actions/checkout@v4
      - run: ls -lah
      - run: |
          sed -i "s|image: mhussain78/hello-flux:.*|image: mhussain78/hello-flux:${{ toJson(github.event.client_payload.image-tag) }}|" ./kubernetes/fluxcd/repositories/hello-flux/deployment.yaml

      - name: commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: updated image tag

